version: 1.0.'{build}'

image:
 - Visual Studio 2017

configuration: Release

platform: x64

environment:
  VCPKG_ROOT: C:\tools\vcpkg

build_script:
  - cmd: vcpkg install libuv
  - cmd: vcpkg install openssl-windows
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake .. -G"Visual Studio 15 2017" -DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x86-windows
  - cmd: cmake --build . --config Debug
  - cmd: examples\Debug\http-client.exe google.com

test_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER% && cd build && tests\Debug\test-uvtls.exe