  
name: uvtls CI

on: [push]

jobs:

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install deps vcpkg
      run: vcpkg install libuv openssl-windows
    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build
    - name: Configure cmake
      working-directory: ${{runner.workspace}}/build
      run: cmake $env:GITHUB_WORKSPACE -DCMAKE_GENERATOR_PLATFORM=Win32 -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"
    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build .
    - name: Tests
      working-directory: ${{runner.workspace}}/build
      run: |
        tests\test-uvtls.exe
