  
name: uvtls CI

on: [push]

jobs:

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: dependencies
      run: vcpkg install libuv openssl-windows
    - name: configure
      run: |
        mkdir build 
        cd build 
        cmake $env:GITHUB_WORKSPACE -G"Visual Studio 15 2017" -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"
    - name: build
      run: cmake --build build
    - name: tests
      run: |
        cd build 
        ./tests/test-uvtls
